In [1]:
import numpy as np
import pandas as pd

import yfinance as yf
from fredapi import Fred

import os

import matplotlib.pyplot as plt
import seaborn as sns

<h1>MacroEconomic Data</h1>

In [2]:
fred_api_key = '7e7047cb386c073a68b26832503fa819'

start = '1990-01-01'
end = '2025-12-31'

In [3]:
macro_variables = [
    'INDPRO', 'W875RX1', 'UNRATE', 'ICSA', 'CPIAUCSL', 'DCOILWTICO', 'VIXCLS',
    'BAA10Y', 'T10Y2Y', 'FEDFUNDS', 'UMCSENT', 'HOUST', 'M2SL'
]

In [4]:
fred = Fred(api_key=fred_api_key)

In [5]:
series_dict = {}

for var in macro_variables:
    series_dict[var] = fred.get_series(var, observation_start=start, observation_end=end)

df_raw = pd.DataFrame(series_dict)

In [6]:
df_raw.head(10)

,INDPRO,W875RX1,UNRATE,ICSA,CPIAUCSL,DCOILWTICO,VIXCLS,BAA10Y,T10Y2Y,FEDFUNDS,UMCSENT,HOUST,M2SL
1990-01-01,61.729,7184.9,5.4,NaN,127.5,NaN,NaN,NaN,NaN,8.23,93.0,1551.0,3166.8
1990-01-02,NaN,NaN,NaN,NaN,NaN,22.88,17.24,1.91,0.07,NaN,NaN,NaN,NaN
1990-01-03,NaN,NaN,NaN,NaN,NaN,23.81,18.19,1.87,0.05,NaN,NaN,NaN,NaN
1990-01-04,NaN,NaN,NaN,NaN,NaN,23.41,19.22,1.86,0.06,NaN,NaN,NaN,NaN
1990-01-05,NaN,NaN,NaN,NaN,NaN,23.07,20.11,1.89,0.09,NaN,NaN,NaN,NaN
1990-01-06,NaN,NaN,NaN,355000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-08,NaN,NaN,NaN,NaN,NaN,21.64,20.26,1.86,0.12,NaN,NaN,NaN,NaN
1990-01-09,NaN,NaN,NaN,NaN,NaN,22.25,22.20,1.84,0.11,NaN,NaN,NaN,NaN
1990-01-10,NaN,NaN,NaN,NaN,NaN,22.90,22.44,1.85,0.12,NaN,NaN,NaN,NaN
1990-01-11,NaN,NaN,NaN,NaN,NaN,23.15,20.05,1.82,0.13,NaN,NaN,NaN,NaN

In [7]:
df_raw.shape

(11332, 13)

In [8]:
df_monthly  = df_raw.resample('ME').last()

In [9]:
df_monthly.head(10)

,INDPRO,W875RX1,UNRATE,ICSA,CPIAUCSL,DCOILWTICO,VIXCLS,BAA10Y,T10Y2Y,FEDFUNDS,UMCSENT,HOUST,M2SL
1990-01-31,61.7290,7184.9,5.4,345000.0,127.5,22.69,25.36,1.68,0.15,8.23,93.0,1551.0,3166.8
1990-02-28,62.2896,7210.5,5.3,350000.0,128.0,21.55,21.99,1.68,0.08,8.24,89.5,1437.0,3179.2
1990-03-31,62.5999,7216.8,5.2,346000.0,128.6,20.34,19.73,1.58,0.01,8.28,91.3,1289.0,3190.1
1990-04-30,62.4359,7262.7,5.4,363000.0,128.9,18.50,19.52,1.50,0.08,8.26,93.9,1248.0,3201.6
1990-05-31,62.6258,7252.9,5.4,359000.0,129.1,17.47,17.37,1.71,0.10,8.18,90.6,1212.0,3200.6
1990-06-30,62.8382,7261.7,5.2,364000.0,129.9,17.05,15.50,1.79,0.19,8.29,88.3,1177.0,3213.7
1990-07-31,62.7284,7289.9,5.5,369000.0,130.5,20.57,21.11,1.77,0.45,8.15,88.2,1171.0,3224.5
1990-08-31,62.9475,7242.0,5.7,394000.0,131.6,27.45,29.90,1.69,0.79,8.13,76.4,1115.0,3242.0
1990-09-30,62.9523,7231.3,5.9,404000.0,132.5,39.53,29.11,1.94,0.80,8.20,72.8,1110.0,3254.6
1990-10-31,62.5845,7159.5,5.9,440000.0,133.4,35.31,30.04,2.13,0.88,8.11,63.9,1014.0,3259.3

In [10]:
df_monthly.shape

(432, 13)

In [11]:
df_monthly.isna().sum()

INDPRO        0
W875RX1       0
UNRATE        1
ICSA          0
CPIAUCSL      1
DCOILWTICO    0
VIXCLS        0
BAA10Y        0
T10Y2Y        0
FEDFUNDS      0
UMCSENT       0
HOUST         0
M2SL          0
dtype: int64

In [12]:
df_monthly['UNRATE'] = df_monthly['UNRATE'].ffill()
df_monthly['CPIAUCSL'] = df_monthly['CPIAUCSL'].ffill()

In [13]:
df_monthly.isna().sum()

INDPRO        0
W875RX1       0
UNRATE        0
ICSA          0
CPIAUCSL      0
DCOILWTICO    0
VIXCLS        0
BAA10Y        0
T10Y2Y        0
FEDFUNDS      0
UMCSENT       0
HOUST         0
M2SL          0
dtype: int64

In [14]:
macro_var = {
    #Real Activity
    "INDPRO": "industrial_production",
    "W875RX1": "real_person_income",

    #Labour Market
    "UNRATE": "unemployment_rate",
    "ICSA": "initial_jobless_claims",

    #Inflation
    "CPIAUCSL": "cpi",
    "DCOILWTICO": "oil_price",

    #Financial Condition
    "VIXCLS": "vix",
    "BAA10Y": "credit_spread",

    #Monetary Policy
    "T10Y2Y": "yield_curve_slope",
    "FEDFUNDS": "fed_funds_rate",

    #Sentiment & Housing
    "UMCSENT": "consumer_sentiment",
    "HOUST": "housing_starts",
    "M2SL": "m2_money_supply"
}

In [15]:
df = df_monthly.rename(columns=macro_var)

In [16]:
df.head()

,industrial_production,real_person_income,unemployment_rate,initial_jobless_claims,cpi,oil_price,vix,credit_spread,yield_curve_slope,fed_funds_rate,consumer_sentiment,housing_starts,m2_money_supply
1990-01-31,61.7290,7184.9,5.4,345000.0,127.5,22.69,25.36,1.68,0.15,8.23,93.0,1551.0,3166.8
1990-02-28,62.2896,7210.5,5.3,350000.0,128.0,21.55,21.99,1.68,0.08,8.24,89.5,1437.0,3179.2
1990-03-31,62.5999,7216.8,5.2,346000.0,128.6,20.34,19.73,1.58,0.01,8.28,91.3,1289.0,3190.1
1990-04-30,62.4359,7262.7,5.4,363000.0,128.9,18.50,19.52,1.50,0.08,8.26,93.9,1248.0,3201.6
1990-05-31,62.6258,7252.9,5.4,359000.0,129.1,17.47,17.37,1.71,0.10,8.18,90.6,1212.0,3200.6

In [17]:
df.to_csv('macro_data.csv')

<h1>Market Data</h1>

In [2]:
tickers = ['VUSTX', 'VFINX']

In [3]:
asset = yf.download(tickers=tickers, start='1990-01-01', end='2025-12-31')['Close']

[*********************100%***********************]  2 of 2 completed

In [4]:
asset.head()

Ticker          VFINX     VUSTX
Date
1990-01-02  16.065907  0.650727
1990-01-03  16.023684  0.648762
1990-01-04  15.892295  0.648762
1990-01-05  15.737456  0.647451
1990-01-08  15.812528  0.645485

In [5]:
gld = pd.read_excel('Gold_price_averages_in_a range_of_currencies_since_1978.xlsx', sheet_name="Monthly_Avg", index_col="Date")

In [6]:
gld = gld.copy()

In [7]:
gld.head()

               USD
Date
1978-01-31  207.83
1978-02-28  227.27
1978-03-31  245.67
1978-04-28  242.05
1978-05-31  239.16

In [8]:
asset_data = asset.join(gld, how="left")

In [9]:
asset_data.head()

                VFINX     VUSTX  USD
Date
1990-01-02  16.065907  0.650727  NaN
1990-01-03  16.023684  0.648762  NaN
1990-01-04  15.892295  0.648762  NaN
1990-01-05  15.737456  0.647451  NaN
1990-01-08  15.812528  0.645485  NaN

In [10]:
asset_data = asset_data.resample('ME').last()

In [11]:
asset_data.head()

                VFINX     VUSTX     USD
Date
1990-01-31  14.723949  0.628845  376.95
1990-02-28  14.911649  0.626791  383.64
1990-03-31  15.324143  0.624541  363.83
1990-04-30  14.940807  0.607535  363.33
1990-05-31  16.388983  0.634859  358.38

In [12]:
market_var = {
    #Bonds
    "VFINX": "index_fund",

    #Equity
    "VUSTX": "treasury_fund",

    #Gold
    "USD": "gold_fund" 
}

In [13]:
asset_data = asset_data.rename(columns=market_var)

In [14]:
asset_data.head()

            index_fund  treasury_fund  gold_fund
Date
1990-01-31   14.723949       0.628845     376.95
1990-02-28   14.911649       0.626791     383.64
1990-03-31   15.324143       0.624541     363.83
1990-04-30   14.940807       0.607535     363.33
1990-05-31   16.388983       0.634859     358.38

In [17]:
asset_data.isna().sum()

index_fund        0
treasury_fund     0
gold_fund        11
dtype: int64

In [21]:
asset_data['gold_fund'] = asset_data['gold_fund'].ffill()

In [22]:
asset_data.isna().sum()

index_fund       0
treasury_fund    0
gold_fund        0
dtype: int64

In [23]:
asset_data.to_csv("market_data.csv")